name: LightGuard
version: 1.0
main: com.mertout.lightguard.LightGuard
api-version: 1.16
authors: [mertout]
description: Advanced Packet-Based Anti-Crash & Exploit Protection System By AI

commands:
  lg:
    permission: lg.admin
    aliases: lightguard
    usage: /lg <args>

permissions:
  lg.admin:
    default: op